---
image: traefik
version: v1.1.43
name: Traefik
description: "[Traefik](https://traefik.io/traefik/) is a leading modern reverse proxy and load balancer that makes deploying microservices easy. Traefik integrates with your existing infrastructure components and configures itself automatically and dynamically."
ext_release: "v3.6.6"
arch:
  - aarch64
  - x86_64
  - armv7
